import { Component } from '@angular/core';
import { PdfGeneratorComponent } from '../pdf-generator/pdf-preview.generator';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [PdfGeneratorComponent],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
})
export class HomeComponent {
  // Define the PDF document properties in real-world units.
  pdfOptions = {
    unit: 'mm',
    format: 'a4',
    orientation: 'p',
    margins: {
      top: 25,
      right: 20,
      bottom: 25,
      left: 20,
    },
    filename: 'final-document.pdf',
  };

  // Provide the image source as a simple prop.
  backgroundImageSrc = 'public/bg.png';

  // Provide clean, semantic HTML content. The generator handles all layout.
  mainContentHtml: string = `
    <h1>Millimeter-Perfect PDF from HTML</h1>
    <p>This layout is defined in <b>millimeters</b>. The preview component converts these measurements to pixels on the fly to create a perfect WYSIWYG experience.</p>
    <p>The final PDF is generated by taking a "screenshot" of each preview page, ensuring the output is identical.</p>
    
    <h2>Feature List</h2>
    <ul>
      <li>Document defined in real-world units (mm).</li>
      <li>Preview is a pixel-perfect visual replica.</li>
      <li>Layout is consistent across all screen sizes.</li>
      <li>Handles complex HTML and CSS in the content.</li>
    </ul>

    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
    
    <h2>This Header Will Be on Page 2</h2>
    <p>The pagination logic calculates the height of the preceding elements and determines that this content must start on a new page, respecting the defined margins.</p>
    <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
  `;
}
